package ast

// This should be autogenerated!!!!
func NewFile() *File {
	return &File{
		Imports:    make([]*ImportDecl, 0),
		Params:     make([]*ParamDecl, 0),
		Statements: make([]Statement, 0),
	}
}

// type SourceRange struct {
// 	End      SourcePos
// 	Filename string
// 	Start    SourcePos
// }

// type SourcePos struct {
// 	Byte   int
// 	Column int
// 	Line   int
// }

// func (sr SourceRange) Clone() SourceRange {
// 	return SourceRange{
// 		End:      sr.End.Clone(),
// 		Start:    sr.Start.Clone(),
// 		Filename: sr.Filename,
// 	}
// }

// func (sp SourcePos) Clone() SourcePos {
// 	return SourcePos{
// 		Byte:   sp.Byte,
// 		Column: sp.Column,
// 		Line:   sp.Line,
// 	}
// }
